- name: install required software
  dnf:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - unzip
      - zip
      - kernel-devel
      - git-core
    state: present
  become: true
